version: '3'

services:
  ros-master:
    image: ros:noetic-ros-core
    command: stdbuf -o L roscore
    network_mode: "host"
    environment:
      - ROS_HOSTNAME=master
      - ROS_MASTER_URI=http://master:11311
      - ROS_IPV6=on

  tortoisebot-ros1-real:
    build: 
      context: ./real
      dockerfile: Dockerfile
    image: real-ros1
    depends_on:
      - ros-master
    network_mode: host
    privileged: true
    tty: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0:rwm
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/gpiomem:/dev/gpiomem
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_IPV6=on

  tortoisebot-ros1-slam-real:
    build:    
      context: ./slam
      dockerfile: Dockerfile
    image: real-slam
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_IPV6=on
    depends_on:
      - tortoisebot-ros1-real
