version: '3'

services:

  ros-master:
    image: ros:noetic-ros-base
    command: stdbuf -o L roscore
    network_mode: "host"
    environment:
      - ROS_HOSTNAME=master
      - ROS_MASTER_URI=http://master:11311
      - ROS_IPV6=on

  tortoisebot-ros1-real:
    image: ros1-real
    container_name: real
    build: 
      context: .
      dockerfile: tortoisebot_ros1_real
    depends_on:
      - ros-master
    network_mode: host
    privileged: true
    tty: true
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/mem
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/gpiomem:/dev/gpiomem
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_IPV6=on

  tortoisebot-ros1-slam-real:
    image: ros1-real-slam
    container_name: slam
    build: 
      context: .
      dockerfile: tortoisebot_ros1_slam
    network_mode: host
    environment:
      - ROS_MASTER_URI=http://master:11311
      - ROS_IPV6=on
    depends_on:
      - tortoisebot-ros1-real